// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// camelsolve
NumericMatrix camelsolve(IntegerMatrix boardstate, IntegerVector unrolled_dice, int num_sims);
RcppExport SEXP camelsolve_camelsolve(SEXP boardstateSEXP, SEXP unrolled_diceSEXP, SEXP num_simsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type boardstate(boardstateSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type unrolled_dice(unrolled_diceSEXP);
    Rcpp::traits::input_parameter< int >::type num_sims(num_simsSEXP);
    rcpp_result_gen = Rcpp::wrap(camelsolve(boardstate, unrolled_dice, num_sims));
    return rcpp_result_gen;
END_RCPP
}
