// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// solve
IntegerMatrix solve(IntegerMatrix boardstate, IntegerVector input_dice, int num_sims);
RcppExport SEXP solver_solve(SEXP boardstateSEXP, SEXP input_diceSEXP, SEXP num_simsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type boardstate(boardstateSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type input_dice(input_diceSEXP);
    Rcpp::traits::input_parameter< int >::type num_sims(num_simsSEXP);
    rcpp_result_gen = Rcpp::wrap(solve(boardstate, input_dice, num_sims));
    return rcpp_result_gen;
END_RCPP
}
