# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_hello_world <- function() {
    .Call('solver_rcpp_hello_world', PACKAGE = 'solver')
}

solve <- function(boardstate, dice) {
    .Call('solver_solve', PACKAGE = 'solver', boardstate, dice)
}

